spring:
  application:
    name : app
  datasource:
    url : jdbc:mysql://localhost:3306/cx
    username : root
    password : 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.app.dto